/**
 * MediaPipe bootstrap helpers.
 *
 * Asset paths prefer LOCAL vendored copies under /mediapipe/ (generated by
 * `bun run assets` / scripts/copy-mediapipe-assets.mjs).  If local loading
 * fails (files not present, 404, network error), the whole initialisation is
 * automatically retried with the original CDN URLs so the app works even
 * without the vendored assets.
 *
 * For an offline / restricted deploy:
 *   Run `bun run assets` once; the script copies the WASM bundle from
 *   node_modules and downloads the model files into public/mediapipe/.
 *   Those paths are gitignored (large binaries).  At runtime the app will
 *   serve them from /mediapipe/wasm and /mediapipe/models without hitting any
 *   external network.
 */

// NOTE: Do NOT import from "@mediapipe/tasks-vision" at module top-level — this
// file is imported lazily inside a useEffect so the WASM loader never runs on
// the server and next build stays safe.
//
// MP_VERSION is injected by next.config.mjs at build time via `env`:
//   require("@mediapipe/tasks-vision/package.json").version
// This ensures the CDN fallback URL always matches the installed package version
// even after a `bun install` bumps the caret range.  @mediapipe/tasks-vision
// does not expose ./package.json in its exports map, so a static import would
// fail the webpack resolver; reading it in next.config.mjs (Node context) then
// passing it as a build constant is the cleanest build-safe alternative.

/** Exact installed version — injected at build time from node_modules. */
const MP_VERSION: string = process.env.NEXT_PUBLIC_MP_VERSION ?? "0.10.35";

// ─── CDN URLs (fallback) ──────────────────────────────────────────────────────

/** jsdelivr-hosted WASM bundle (matches the installed npm version). */
const CDN_WASM_BASE_URL = `https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@${MP_VERSION}/wasm`;

/** Google-hosted hand landmarker model (float16 full model, ~9 MB). */
const CDN_HAND_MODEL_URL =
  "https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/latest/hand_landmarker.task";

/**
 * Google-hosted pose landmarker model (lite variant, ~3 MB).
 * Lite gives adequate landmark accuracy for face bbox computation at lower
 * inference cost than the full or heavy variants.
 */
const CDN_POSE_MODEL_URL =
  "https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/latest/pose_landmarker_lite.task";

/**
 * Google-hosted selfie segmenter model (~1 MB, single-class person mask).
 *
 * Model: selfie_segmenter (general variant, good for desk/webcam framing).
 * Outputs a single confidence mask channel (Float32) in [0, 1] per pixel
 * where 1.0 = definitely person, 0.0 = definitely background.
 *
 * NOTE: the ImageSegmenter model ships as a `.tflite` asset (unlike the
 * HandLandmarker / PoseLandmarker, which use `.task` bundles). Using `.task`
 * here returns a 404.
 *
 * The "selfie_multiclass" variant (5-class hair/skin/clothing/etc.) is NOT
 * used here — we only need a binary person vs. background probability.
 */
const CDN_SEGMENTER_MODEL_URL =
  "https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_segmenter/float16/latest/selfie_segmenter.tflite";

// ─── Local (vendored) URLs (primary) ─────────────────────────────────────────

/** Vendored WASM bundle served from Next.js public/. */
const LOCAL_WASM_BASE_URL = "/mediapipe/wasm";

const LOCAL_HAND_MODEL_URL = "/mediapipe/models/hand_landmarker.task";
const LOCAL_POSE_MODEL_URL = "/mediapipe/models/pose_landmarker_lite.task";
const LOCAL_SEGMENTER_MODEL_URL = "/mediapipe/models/selfie_segmenter.tflite";

// ─── Shared types ─────────────────────────────────────────────────────────────

export interface HandLandmarkerHandle {
  /** The underlying MediaPipe HandLandmarker instance. */
  landmarker: import("@mediapipe/tasks-vision").HandLandmarker;
  /** Call this to free WASM resources. */
  close: () => void;
}

export interface PoseLandmarkerHandle {
  /** The underlying MediaPipe PoseLandmarker instance. */
  landmarker: import("@mediapipe/tasks-vision").PoseLandmarker;
  /** Call this to free WASM resources. */
  close: () => void;
}

export interface ImageSegmenterHandle {
  /** The underlying MediaPipe ImageSegmenter instance. */
  segmenter: import("@mediapipe/tasks-vision").ImageSegmenter;
  /** Call this to free WASM resources. */
  close: () => void;
}

/**
 * All three tracking handles, created from a single shared FilesetResolver so
 * the WASM bundle is only fetched once.
 */
export interface TrackingHandles {
  hand: HandLandmarkerHandle;
  pose: PoseLandmarkerHandle;
  /** Iter 18 — selfie segmenter producing a confidence mask for person pixels. */
  segmenter: ImageSegmenterHandle;
}

// ─── Factory ──────────────────────────────────────────────────────────────────

/**
 * Internal: attempt to initialise all three MediaPipe trackers with the given
 * WASM base URL and model paths.  Throws on any failure.
 */
async function attemptInit(
  FilesetResolver: (typeof import("@mediapipe/tasks-vision"))["FilesetResolver"],
  HandLandmarker: (typeof import("@mediapipe/tasks-vision"))["HandLandmarker"],
  PoseLandmarker: (typeof import("@mediapipe/tasks-vision"))["PoseLandmarker"],
  ImageSegmenter: (typeof import("@mediapipe/tasks-vision"))["ImageSegmenter"],
  wasmBaseUrl: string,
  handModelUrl: string,
  poseModelUrl: string,
  segmenterModelUrl: string
): Promise<TrackingHandles> {
  const vision = await FilesetResolver.forVisionTasks(wasmBaseUrl);

  // Use allSettled so that if one creation rejects we can close any that
  // succeeded before propagating the error — preventing WASM heap leaks.
  const results = await Promise.allSettled([
    HandLandmarker.createFromOptions(vision, {
      baseOptions: {
        modelAssetPath: handModelUrl,
        delegate: "GPU",
      },
      runningMode: "VIDEO",
      numHands: 2,
    }),
    PoseLandmarker.createFromOptions(vision, {
      baseOptions: {
        modelAssetPath: poseModelUrl,
        delegate: "GPU",
      },
      runningMode: "VIDEO",
      numPoses: 1,
    }),
    // Iter 18 — Selfie segmenter: confidence masks mode gives a Float32 [0,1]
    // person-probability per pixel, which we upload directly as a DataTexture.
    // outputCategoryMask is disabled; we use confidence masks for soft edges.
    ImageSegmenter.createFromOptions(vision, {
      baseOptions: {
        modelAssetPath: segmenterModelUrl,
        delegate: "GPU",
      },
      runningMode: "VIDEO",
      outputCategoryMask: false,
      outputConfidenceMasks: true,
    }),
  ]);

  // If any creation failed, close every successfully-created landmarker to
  // free WASM heap before throwing (so createTrackingHandles' catch can retry).
  const rejected = results.find((r) => r.status === "rejected");
  if (rejected) {
    for (const result of results) {
      if (result.status === "fulfilled") {
        try {
          result.value.close();
        } catch {
          // best-effort cleanup; ignore errors during teardown
        }
      }
    }
    throw (rejected as PromiseRejectedResult).reason;
  }

  // All three succeeded — unpack the fulfilled values.
  const [handResult, poseResult, segmenterResult] = results as [
    PromiseFulfilledResult<import("@mediapipe/tasks-vision").HandLandmarker>,
    PromiseFulfilledResult<import("@mediapipe/tasks-vision").PoseLandmarker>,
    PromiseFulfilledResult<import("@mediapipe/tasks-vision").ImageSegmenter>,
  ];
  const handLandmarker = handResult.value;
  const poseLandmarker = poseResult.value;
  const imageSegmenter = segmenterResult.value;

  return {
    hand: {
      landmarker: handLandmarker,
      close: () => handLandmarker.close(),
    },
    pose: {
      landmarker: poseLandmarker,
      close: () => poseLandmarker.close(),
    },
    segmenter: {
      segmenter: imageSegmenter,
      close: () => imageSegmenter.close(),
    },
  };
}

/**
 * Initialise the MediaPipe WASM runtime ONCE, then create both a HandLandmarker,
 * a PoseLandmarker, and an ImageSegmenter from the same fileset.
 *
 * - HandLandmarker: VIDEO mode, 2 hands, GPU delegate.
 * - PoseLandmarker: VIDEO mode, 1 pose, GPU delegate (lite model).
 * - ImageSegmenter: VIDEO mode, confidence masks, GPU delegate.
 *
 * Asset loading strategy:
 *   1. Try LOCAL vendored assets (public/mediapipe/, generated by `bun run assets`).
 *   2. On any failure, fall back to CDN URLs (jsdelivr WASM + Google Storage models).
 *
 * Must be called from a browser context (not during SSR).
 * Throws if BOTH local and CDN initialisation fail, so the caller can surface
 * the error.
 */
export async function createTrackingHandles(): Promise<TrackingHandles> {
  // Dynamic import — keeps the WASM loader out of the server bundle.
  const { FilesetResolver, HandLandmarker, PoseLandmarker, ImageSegmenter } =
    await import("@mediapipe/tasks-vision");

  // ── Attempt 1: local vendored assets ──────────────────────────────────────
  try {
    console.log("[tracking] trying local vendored MediaPipe assets...");
    const handles = await attemptInit(
      FilesetResolver,
      HandLandmarker,
      PoseLandmarker,
      ImageSegmenter,
      LOCAL_WASM_BASE_URL,
      LOCAL_HAND_MODEL_URL,
      LOCAL_POSE_MODEL_URL,
      LOCAL_SEGMENTER_MODEL_URL
    );
    console.log("[tracking] local assets loaded successfully.");
    return handles;
  } catch (localErr) {
    console.warn(
      "[tracking] local asset loading failed — falling back to CDN:",
      localErr
    );
  }

  // ── Attempt 2: CDN fallback ────────────────────────────────────────────────
  try {
    console.log("[tracking] loading MediaPipe from CDN (fallback)...");
    const handles = await attemptInit(
      FilesetResolver,
      HandLandmarker,
      PoseLandmarker,
      ImageSegmenter,
      CDN_WASM_BASE_URL,
      CDN_HAND_MODEL_URL,
      CDN_POSE_MODEL_URL,
      CDN_SEGMENTER_MODEL_URL
    );
    console.log("[tracking] CDN assets loaded successfully.");
    return handles;
  } catch (cdnErr) {
    console.error("[tracking] CDN fallback also failed:", cdnErr);
    throw cdnErr;
  }
}
